INSERT INTO answers (id, question_id, answer, is_correct) VALUES (1, 1, 'Canberra', TRUE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (2, 1, 'Sydney', FALSE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (3, 1, 'Melbourne', FALSE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (4, 1, 'Brisbane', FALSE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (5, 2, 'Harper Lee', TRUE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (6, 2, 'Mark Twain', FALSE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (7, 2, 'F. Scott Fitzgerald', FALSE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (8, 2, 'Ernest Hemingway', FALSE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (9, 3, 'Au', TRUE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (10, 3, 'Ag', FALSE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (11, 3, 'Fe', FALSE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (12, 3, 'Pb', FALSE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (13, 4, 'Pacific Ocean', TRUE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (14, 4, 'Atlantic Ocean', FALSE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (15, 4, 'Indian Ocean', FALSE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (16, 4, 'Arctic Ocean', FALSE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (17, 5, '1969', TRUE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (18, 5, '1971', FALSE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (19, 5, '1965', FALSE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (20, 5, '1973', FALSE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (21, 6, 'Objective logic (Thinking)', TRUE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (22, 6, 'Personal values (Feeling)', FALSE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (23, 7, 'Social interaction (Extraversion)', TRUE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (24, 7, 'Solitary activities (Introversion)', FALSE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (25, 8, 'Yes (Linguistic)', TRUE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (26, 8, 'No (Other)', FALSE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (27, 9, 'Yes (Interpersonal)', TRUE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (28, 9, 'No (Other)', FALSE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (29, 10, 'Very often', TRUE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (30, 10, 'Rarely', FALSE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (31, 11, 'Yes', TRUE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (32, 11, 'No', FALSE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (33, 12, 'Yes', TRUE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (34, 12, 'No', FALSE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (35, 13, 'Very comfortable', TRUE);
INSERT INTO answers (id, question_id, answer, is_correct) VALUES (36, 13, 'Uncomfortable', FALSE);