INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (1, 'GPA Requirement', 'ACADEMIC', '3.0', 1);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (2, 'English Language Test', 'LANGUAGE', 'IELTS 6.5', 1);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (3, 'Entrance Exam', 'OTHER', 'Pass', 1);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (4, 'Recommendation Letter', 'OTHER', '2 Letters', 1);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (5, 'GPA Requirement', 'ACADEMIC', '3.0', 2);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (6, 'English Language Test', 'LANGUAGE', 'IELTS 6.5', 2);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (7, 'Entrance Exam', 'OTHER', 'Pass', 2);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (8, 'Recommendation Letter', 'OTHER', '2 Letters', 2);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (9, 'GPA Requirement', 'ACADEMIC', '3.0', 3);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (10, 'English Language Test', 'LANGUAGE', 'IELTS 6.5', 3);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (11, 'Entrance Exam', 'OTHER', 'Pass', 3);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (12, 'Recommendation Letter', 'OTHER', '2 Letters', 3);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (13, 'GPA Requirement', 'ACADEMIC', '3.0', 4);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (14, 'English Language Test', 'LANGUAGE', 'IELTS 6.5', 4);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (15, 'Entrance Exam', 'OTHER', 'Pass', 4);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (16, 'Recommendation Letter', 'OTHER', '2 Letters', 4);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (17, 'GPA Requirement', 'ACADEMIC', '3.0', 5);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (18, 'English Language Test', 'LANGUAGE', 'IELTS 6.5', 5);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (19, 'Entrance Exam', 'OTHER', 'Pass', 5);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (20, 'Recommendation Letter', 'OTHER', '2 Letters', 5);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (21, 'GPA Requirement', 'ACADEMIC', '3.0', 6);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (22, 'English Language Test', 'LANGUAGE', 'IELTS 6.5', 6);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (23, 'Entrance Exam', 'OTHER', 'Pass', 6);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (24, 'Recommendation Letter', 'OTHER', '2 Letters', 6);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (25, 'GPA Requirement', 'ACADEMIC', '3.0', 7);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (26, 'English Language Test', 'LANGUAGE', 'IELTS 6.5', 7);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (27, 'Entrance Exam', 'OTHER', 'Pass', 7);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (28, 'Recommendation Letter', 'OTHER', '2 Letters', 7);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (29, 'GPA Requirement', 'ACADEMIC', '3.0', 8);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (30, 'English Language Test', 'LANGUAGE', 'IELTS 6.5', 8);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (31, 'Entrance Exam', 'OTHER', 'Pass', 8);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (32, 'Recommendation Letter', 'OTHER', '2 Letters', 8);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (33, 'GPA Requirement', 'ACADEMIC', '3.0', 9);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (34, 'English Language Test', 'LANGUAGE', 'IELTS 6.5', 9);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (35, 'Entrance Exam', 'OTHER', 'Pass', 9);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (36, 'Recommendation Letter', 'OTHER', '2 Letters', 9);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (37, 'GPA Requirement', 'ACADEMIC', '3.0', 10);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (38, 'English Language Test', 'LANGUAGE', 'IELTS 6.5', 10);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (39, 'Entrance Exam', 'OTHER', 'Pass', 10);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (40, 'Recommendation Letter', 'OTHER', '2 Letters', 10);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (41, 'GPA Requirement', 'ACADEMIC', '3.0', 11);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (42, 'English Language Test', 'LANGUAGE', 'IELTS 6.5', 11);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (43, 'Entrance Exam', 'OTHER', 'Pass', 11);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (44, 'Recommendation Letter', 'OTHER', '2 Letters', 11);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (45, 'GPA Requirement', 'ACADEMIC', '3.0', 12);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (46, 'English Language Test', 'LANGUAGE', 'IELTS 6.5', 12);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (47, 'Entrance Exam', 'OTHER', 'Pass', 12);
INSERT INTO institution_enrollment_requirements (id, name, type, value, institution_id) VALUES (48, 'Recommendation Letter', 'OTHER', '2 Letters', 12);