INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (1, 'High School Diploma', 1);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (2, 'Passport/ID', 1);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (3, 'Medical Certificate', 1);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (4, 'Application Form', 1);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (5, 'Photo', 1);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (6, 'High School Diploma', 2);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (7, 'Passport/ID', 2);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (8, 'Medical Certificate', 2);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (9, 'Application Form', 2);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (10, 'Photo', 2);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (11, 'High School Diploma', 3);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (12, 'Passport/ID', 3);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (13, 'Medical Certificate', 3);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (14, 'Application Form', 3);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (15, 'Photo', 3);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (16, 'High School Diploma', 4);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (17, 'Passport/ID', 4);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (18, 'Medical Certificate', 4);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (19, 'Application Form', 4);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (20, 'Photo', 4);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (21, 'High School Diploma', 5);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (22, 'Passport/ID', 5);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (23, 'Medical Certificate', 5);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (24, 'Application Form', 5);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (25, 'Photo', 5);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (26, 'High School Diploma', 6);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (27, 'Passport/ID', 6);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (28, 'Medical Certificate', 6);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (29, 'Application Form', 6);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (30, 'Photo', 6);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (31, 'High School Diploma', 7);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (32, 'Passport/ID', 7);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (33, 'Medical Certificate', 7);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (34, 'Application Form', 7);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (35, 'Photo', 7);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (36, 'High School Diploma', 8);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (37, 'Passport/ID', 8);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (38, 'Medical Certificate', 8);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (39, 'Application Form', 8);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (40, 'Photo', 8);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (41, 'High School Diploma', 9);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (42, 'Passport/ID', 9);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (43, 'Medical Certificate', 9);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (44, 'Application Form', 9);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (45, 'Photo', 9);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (46, 'High School Diploma', 10);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (47, 'Passport/ID', 10);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (48, 'Medical Certificate', 10);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (49, 'Application Form', 10);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (50, 'Photo', 10);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (51, 'High School Diploma', 11);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (52, 'Passport/ID', 11);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (53, 'Medical Certificate', 11);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (54, 'Application Form', 11);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (55, 'Photo', 11);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (56, 'High School Diploma', 12);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (57, 'Passport/ID', 12);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (58, 'Medical Certificate', 12);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (59, 'Application Form', 12);
INSERT INTO institution_enrollment_documents (id, name, institution_id) VALUES (60, 'Photo', 12);